@startuml
!include ../src/EventStorming.iuml

SubDomain("My Sub-Domain", SD1) {
    IntegrationEvent('foo bar', 'FooBar', $Aggregate('Registered user'))
    DomainEvent('Bla bla', BlaBla)
    '$Aggregate('Registered user')
}

!$user = 'Bla'
DomainEvent("Foo 2", Foo2, $User(Qus), $Command(Bas2), $Aggregate($user))
DomainEvent("Foo 21", Foo21, $User(Qus1), $Command(Bas21), $Aggregate($user))
DomainEvent("Event with Policy", EventWithPolicy, $Policy(MyPolicy), $Command(MyCommand), $Aggregate(MyAggregate))
DomainEvent("Event with Policy and User", EventWithPolicyAndUser, $User(Hans), $Policy(MyPolicy), $Command(MyCommand), $Aggregate(MyAggregate))

Foo2 -> Foo21_User

note as foo
    This is a note
end note

Foo2_Aggregate . foo



@enduml