!include ./Theme.iuml
!include ./Utils.iuml
!include ./Stickies.iuml

!unquoted procedure SubDomain($label, $id = '')
    !if $id == ''
        storage "$label" #LightBlue
    !else
        storage "$label" as $id #LightBlue
    !endif
!endprocedure

!unquoted procedure Process($label, $id = '')
    !if $id == ''
        rectangle "$label"
    !else
        rectangle "$label" as $id
    !endif
!endprocedure

!function $GetAggregate($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !if ($IsStickyAggregate($sticky1))
       !return $sticky1
    !endif

    !if ($IsStickyAggregate($sticky2))
       !return $sticky2
    !endif

    !if ($IsStickyAggregate($sticky3))
       !return $sticky3
    !endif

    !if ($IsStickyAggregate($sticky4))
       !return $sticky3
    !endif

    !if ($IsStickyAggregate($sticky5))
       !return $sticky4
    !endif

    !if ($IsStickyAggregate($sticky6))
       !return $sticky6
    !endif

    !return ''
!endprocedure

!function $GetCommand($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !if ($IsStickyCommand($sticky1))
       !return $sticky1
    !endif

    !if ($IsStickyCommand($sticky2))
       !return $sticky2
    !endif

    !if ($IsStickyCommand($sticky3))
       !return $sticky3
    !endif

    !if ($IsStickyCommand($sticky4))
       !return $sticky3
    !endif

    !if ($IsStickyCommand($sticky5))
       !return $sticky4
    !endif

    !if ($IsStickyCommand($sticky6))
       !return $sticky6
    !endif

    !return ''
!endprocedure

!function $GetUser($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !if ($IsStickyUser($sticky1))
       !return $sticky1
    !endif

    !if ($IsStickyUser($sticky2))
       !return $sticky2
    !endif

    !if ($IsStickyUser($sticky3))
       !return $sticky3
    !endif

    !if ($IsStickyUser($sticky4))
       !return $sticky3
    !endif

    !if ($IsStickyUser($sticky5))
       !return $sticky4
    !endif

    !if ($IsStickyUser($sticky6))
       !return $sticky6
    !endif

    !return ''
!endprocedure

!function $GetPolicy($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !if ($IsStickyPolicy($sticky1))
       !return $sticky1
    !endif

    !if ($IsStickyPolicy($sticky2))
       !return $sticky2
    !endif

    !if ($IsStickyPolicy($sticky3))
       !return $sticky3
    !endif

    !if ($IsStickyPolicy($sticky4))
       !return $sticky3
    !endif

    !if ($IsStickyPolicy($sticky5))
       !return $sticky4
    !endif

    !if ($IsStickyPolicy($sticky6))
       !return $sticky6
    !endif

    !return ''
!endprocedure

!function $GetSystem($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !if ($IsStickySystem($sticky1))
       !return $sticky1
    !endif

    !if ($IsStickySystem($sticky2))
       !return $sticky2
    !endif

    !if ($IsStickySystem($sticky3))
       !return $sticky3
    !endif

    !if ($IsStickySystem($sticky4))
       !return $sticky3
    !endif

    !if ($IsStickySystem($sticky5))
       !return $sticky4
    !endif

    !if ($IsStickySystem($sticky6))
       !return $sticky6
    !endif

    !return ''
!endprocedure

!function $GetReadModel($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !if ($IsStickyReadModel($sticky1))
       !return $sticky1
    !endif

    !if ($IsStickyReadModel($sticky2))
       !return $sticky2
    !endif

    !if ($IsStickyReadModel($sticky3))
       !return $sticky3
    !endif

    !if ($IsStickyReadModel($sticky4))
       !return $sticky3
    !endif

    !if ($IsStickyReadModel($sticky5))
       !return $sticky4
    !endif

    !if ($IsStickyReadModel($sticky6))
       !return $sticky6
    !endif

    !return ''
!endprocedure

!unquoted procedure PrintAggregate($aggregate, $eventId)
    !$aggregate = $WithId($aggregate, $eventId + '_Aggregate')

    $aggregate

    'ID can be another than Aggregate when it was set explicitly
    !$__aggregateId__ = $GetId($aggregate)
    $__aggregateId__ -- $eventId
!endprocedure

!unquoted procedure $EventBlock($event, $sticky1='', $sticky2='', $sticky3='', $sticky4='', $sticky5='', $sticky6='')
    !assert $GetStereotype($event) == 'DomainEvent' || $GetStereotype($event) == 'IntegrationEvent'

    'All variable names with double underscores to omit name conflicts
    !$__eventId__ = $GetId($event)
    !$__firstStickyId__ = $__eventId__

    ' There are no arrays in PlantUML, so we have to check each sticky separately
    !$__aggregate__ = $GetAggregate($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !$__command__ = $GetCommand($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !$__user__ = $GetUser($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !$__policy__ = $GetPolicy($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !$__system__ = $GetSystem($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)
    !$__readModel__ = $GetReadModel($sticky1, $sticky2, $sticky3, $sticky4, $sticky5, $sticky6)

    !$__inputId__ = $__eventId__ + '_Input'
    !$__input__ = 'queue " " as ' + $__inputId__ + ' #Black;line:Black'

    $__input__
    $event

    !if ($__aggregate__ != '')
        PrintAggregate($__aggregate__, $__eventId__)
    !endif

    'A function cannot print something, so the following code cannot be extracted to functions.
    !$__systemId__ = ''

    !if ($__system__ != '')
        !$__system__ = $WithId($__system__, $__eventId__ + '_System')
        $__system__

        !$__systemId__ = $GetId($__system__)
        $__systemId__ - $__eventId__

        !$__firstStickyId__ = $__systemId__
    !endif

    !$__commandId__ = ''

    !if ($__command__ != '')
        !$__command__ = $WithId($__command__, $__eventId__ + '_Command')
        $__command__

        !$__commandId__ = $GetId($__command__)
        !$__firstStickyId__ = $__commandId__

        !if ($__systemId__ != '')
            $__commandId__ - $__systemId__
        !else
            $__commandId__ - $__eventId__
        !endif

        !if ($__policy__ != '')
            !$__policy__ = $WithId($__policy__, $__eventId__ + '_Policy')
            $__policy__

            !$__policyId__ = $GetId($__policy__)
            $__policyId__ - $__commandId__

            !$__firstStickyId__ = $__policyId__
        !endif

        !if ($__user__ != '')
            PrintUser($__user__, $__eventId__, $__commandId__, $__inputId__)
            !$__user__ = $WithId($__user__, $__eventId__ + '_User')

            $__user__

            !$__userId__ = $GetId($__user__)
            $__userId__ - $__commandId__
            $__inputId__ -[hidden] $__userId__

            !$__firstStickyId__ = $__userId__
        !endif

        !if ($__user__ != '' && $__policy__ != '')
            $__userId__ -[hidden] $__policyId__
            $__policyId__ -[hidden] $__userId__
        !endif
    !else
        !assert $__command__ == '' && $__user__ == '' : "User stickies can only be set with a Command."
        !assert $__command__ == '' && $__policy__ == '' : "Policy stickies can only be set with a Command."
    !endif

    !if ($__readModel__ != '')
        !$__readModel__ = $WithId($__readModel__, $__eventId__ + '_ReadModel')
        $__readModel__

        !$__readModelId__ = $GetId($__readModel__)
        $__eventId__ -[hidden]- $__readModelId__

        !if ($__commandId__ != '')
            $__commandId__ -[hidden]- $__readModelId__
        !endif
    !endif

    $__inputId__ - $__firstStickyId__
!endprocedure