!function $PrintEventStormingSticky($shape, $stereotype, $label, $id = '')
    !if ($id != '')
        !return $shape + ' "' + $label + '"' + ' as ' + $id + ' <<' + $stereotype + '>>'
    !endif

    !return $shape + ' "' + $label + '" <<' + $stereotype + '>>'
!endfunction

!function $DomainEvent($label, $id)
    !return $PrintEventStormingSticky('file', 'DomainEvent', $label, $id)
!endfunction

!unquoted procedure IntegrationEvent($label, $id)
    $DomainEvent($label, $id)
!endfunction

!function $IntegrationEvent($label, $id)
    !return $PrintEventStormingSticky('file', 'IntegrationEvent', $label, $id)
!endfunction

!unquoted procedure IntegrationEvent($label, $id)
    $IntegrationEvent($label, $id)
!endfunction

!unquoted procedure Blocker($label, $id)
    $PrintEventStormingSticky('file', 'Blocker', $label, $id)
!endfunction

!unquoted procedure Opportunity($label, $id)
    $PrintEventStormingSticky('file', 'Opportunity', $label, $id)
!endfunction

!function $Aggregate($label, $id='')
    !return $PrintEventStormingSticky('file', 'Aggregate', $label, $id)
!endfunction

!function $Command($label, $id='')
    !return $PrintEventStormingSticky('file', 'Command', $label, $id)
!endfunction

!function $User($label, $id='')
    !return $PrintEventStormingSticky('person', 'User', $label, $id)
!endfunction

!function $ReadModel($label, $id='')
    !return $PrintEventStormingSticky('file', 'ReadModel', $label, $id)
!endfunction

!function $Policy($label, $id='')
    !return $PrintEventStormingSticky('file', 'Policy', $label, $id)
!endfunction

!function $System($label, $id='')
    !return $PrintEventStormingSticky('file', 'System', $label, $id)
!endfunction
